name: .NET CI

env:
  PROJECT_NAME: ServerLauncher

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: .Net ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        framework: ['7.0']
        include:
        - os: ubuntu-20.04
          target: linux-x64
        - os: windows-latest
          target: win-x64
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - if: matrix.os == 'ubuntu-20.04'
        name: Install Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libkrb5-dev make gcc libc-dev cmake llvm

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.framework }}

      - name: Install dependencies for ${{ matrix.target }}
        run: dotnet restore -r ${{ matrix.target }}

      - name: Build ${{ matrix.target }}
        run: dotnet publish "${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj" -r ${{ matrix.target }} -c release -o "${{ github.workspace }}/builds/${{ matrix.framework }}/${{ matrix.target }}"

      - name: Upload ${{ matrix.target }} Build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.target }}-${{ matrix.framework }}
          path: ${{ github.workspace }}/builds/${{ matrix.framework }}/${{ matrix.target }}/*${{ env.PROJECT_NAME }}*

  release:
    name: Release
    needs: build
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download all builds
        uses: actions/download-artifact@v3
        with:
          pattern: ${{ env.PROJECT_NAME }}-*-*
          path: builds
          merge-multiple: true
      - name: Release All
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'builds/*/*'
          bodyFile: ".github/release-body.md"
          commit: ${{ github.sha }}
          draft: false
          prerelease: false
